# when using the default proxy server port
local_backend: false

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '/content/blog/'
    create: true
    # slug: 'index'
    media_folder: '/static/images'
    public_folder: '../../static/images'
    path: '{{title}}/index'
    nested:
      depth: 3
    editor:
      preview: false
    fields:
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Tags', name: 'tag', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string', default: "Jino Antony" }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Cover Image', name: 'coverImage', widget: 'image', media_folder: "" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }